version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: "my-sql"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ROOT_DATABASE=backend
      - MYSQL_ROOT_PASSWORD=X!gJ`$p~TJ<>`2u.
      - MYSQL_DATABASE=backend
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=backend
      - DB_HOST=db
    restart: always


  frontend:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    restart: always
